services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64  # Forces x86_64 emulation on Apple Silicon
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "morentdbpassword"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: