// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morent.Infrastructure.Data;

#nullable disable

namespace Morent.Infrastructure.Migrations
{
    [DbContext(typeof(MorentDbContext))]
    [Migration("20250520101401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Morent.Core.MediaAggregate.MorentImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ImageId");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelTankCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gearbox")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "ModelName", "Year")
                        .IsUnique();

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("Morent.Core.MorentPaymentAggregate.MorentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Morent.Core.MorentPaymentAggregate.PaymentProvider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeePercent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LogoImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogoImageId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Morent.Core.MorentRentalAggregate.MorentRental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MorentCarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("MorentCarId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Morent.Core.MorentReviewAggregate.MorentReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CarId");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Morent.Core.MorentUserAggregate.MorentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfileImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImageId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCar", b =>
                {
                    b.HasOne("Morent.Core.MorentCarAggregate.MorentCarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Morent.Core.ValueObjects.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("MorentCarId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationAddress");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationCity");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LocationCountry");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("LocationLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("LocationLongitude");

                            b1.HasKey("MorentCarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("MorentCarId");
                        });

                    b.OwnsOne("Morent.Core.ValueObjects.Money", "PricePerDay", b1 =>
                        {
                            b1.Property<Guid>("MorentCarId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("MorentCarId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("MorentCarId");
                        });

                    b.Navigation("CarModel");

                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("PricePerDay")
                        .IsRequired();
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCarImage", b =>
                {
                    b.HasOne("Morent.Core.MorentCarAggregate.MorentCar", null)
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morent.Core.MediaAggregate.MorentImage", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Morent.Core.MorentPaymentAggregate.MorentPayment", b =>
                {
                    b.HasOne("Morent.Core.MorentPaymentAggregate.PaymentProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morent.Core.MorentRentalAggregate.MorentRental", null)
                        .WithOne()
                        .HasForeignKey("Morent.Core.MorentPaymentAggregate.MorentPayment", "RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Morent.Core.ValueObjects.Money", "PaymentAmount", b1 =>
                        {
                            b1.Property<Guid>("MorentPaymentId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT");

                            b1.HasKey("MorentPaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("MorentPaymentId");
                        });

                    b.Navigation("PaymentAmount")
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Morent.Core.MorentPaymentAggregate.PaymentProvider", b =>
                {
                    b.HasOne("Morent.Core.MediaAggregate.MorentImage", null)
                        .WithMany()
                        .HasForeignKey("LogoImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Morent.Core.MorentRentalAggregate.MorentRental", b =>
                {
                    b.HasOne("Morent.Core.MorentCarAggregate.MorentCar", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Morent.Core.MorentCarAggregate.MorentCar", null)
                        .WithMany("Rentals")
                        .HasForeignKey("MorentCarId");

                    b.HasOne("Morent.Core.MorentPaymentAggregate.MorentPayment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.HasOne("Morent.Core.MorentUserAggregate.MorentUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Morent.Core.ValueObjects.Location", "DropoffLocation", b1 =>
                        {
                            b1.Property<Guid>("MorentRentalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasColumnType("TEXT")
                                .HasColumnName("DropoffLocationAddress");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT")
                                .HasColumnName("DropoffLocationCity");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT")
                                .HasColumnName("DropoffLocationCountry");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("DropoffLocationLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("DropoffLocationLongitude");

                            b1.HasKey("MorentRentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("MorentRentalId");
                        });

                    b.OwnsOne("Morent.Core.ValueObjects.Location", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("MorentRentalId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .HasColumnType("TEXT")
                                .HasColumnName("PickupLocationAddress");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT")
                                .HasColumnName("PickupLocationCity");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT")
                                .HasColumnName("PickupLocationCountry");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("PickupLocationLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("PickupLocationLongitude");

                            b1.HasKey("MorentRentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("MorentRentalId");
                        });

                    b.OwnsOne("Morent.Core.ValueObjects.Money", "TotalCost", b1 =>
                        {
                            b1.Property<Guid>("MorentRentalId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("MorentRentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("MorentRentalId");
                        });

                    b.OwnsOne("Morent.Core.ValueObjects.DateRange", "RentalPeriod", b1 =>
                        {
                            b1.Property<Guid>("MorentRentalId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT");

                            b1.HasKey("MorentRentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("MorentRentalId");
                        });

                    b.Navigation("Car");

                    b.Navigation("DropoffLocation")
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("PickupLocation")
                        .IsRequired();

                    b.Navigation("RentalPeriod")
                        .IsRequired();

                    b.Navigation("TotalCost")
                        .IsRequired();
                });

            modelBuilder.Entity("Morent.Core.MorentReviewAggregate.MorentReview", b =>
                {
                    b.HasOne("Morent.Core.MorentCarAggregate.MorentCar", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Morent.Core.MorentUserAggregate.MorentUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morent.Core.MorentUserAggregate.MorentUser", b =>
                {
                    b.HasOne("Morent.Core.MediaAggregate.MorentImage", null)
                        .WithMany()
                        .HasForeignKey("ProfileImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Morent.Core.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("MorentUserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("MorentUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("MorentUserId");
                        });

                    b.OwnsMany("Morent.Core.MorentUserAggregate.MorentUserOAuthLogin", "OAuthLogins", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.HasIndex("Provider", "ProviderKey")
                                .IsUnique();

                            b1.ToTable("MorentUserOAuthLogin");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Morent.Core.ValueObjects.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("Token");

                            b1.HasIndex("UserId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("OAuthLogins");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Morent.Core.MorentCarAggregate.MorentCar", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rentals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Morent.Core.MorentUserAggregate.MorentUser", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
